I've done it
shulgadanilazxc/cs102 pull request #1
Opened 2020-10-10 15:54 UTC by shulgadanilazxc

**Шульга Данила Андреевич К3143**

2020-10-17 19:50 UTC, anastasiiaCher commented
**Цезарь**
encrypt_caesar: Кажется, строка 3 не несет в себе никакого смысла. Следите за чистотой кода (пробелы, отступы - это все важно). В строке 8 раскройте/уберите лишние скобки.
decrypt_caesar: необходимо реализовать как самостоятельную функцию, а не encrypt_caesar с -shift.
Переменные должны иметь осмысленные именования (х, увы, таковым не является).
**Виженер**
Не проходит юнит-тесты. Не учитывается ситуация, когда строка состоит из нескольких слов, разделенных пробелами. Ошибка 
```
ciphertext += "".join([x[x.index((plaintext[i])) + x.index(keyword[i])]])
ValueError: substring not found
```
Еще раз: следите за чистотой кода и скобками.
**RSA**
Не проходит юнит-тесты.
Вы совершенно спокойно можете удалить pass в конце каждой функции.
is_prime: единица не является простым числом.
gcd: на выполнение функции расходуется нерациональное количество времени. Необходимо оптимизировать подход.
multiplicative_inverse: работает не совсем корректно. Например, для `multiplicative_inverse(1110, 2560)` и для `multiplicative_inverse(100000, 550)` выводится `None` или 0, т.к вы добавили `return 0` (должно быть 2447 и 5, соответственно).

СЛЕДИТЕ ЗА ЧИСТОТОЙ КОДА!

2020-10-26 18:10 UTC, anastasiiaCher commented
**Цезарь:** не очень хорошо, конечно, что вы содаете переменную с алфавитом и не используете функции `ord()` и `chr()`, как рекомендуется в описании работы. Но реализация рабочая и имеет место быть. Только верните доктесты на место (это те комменты в тройных кавычках в начале каждой функции.
**Виженер:** юнит-тесты по-прежнему не проходят.
![image](https://user-images.githubusercontent.com/28839610/97210716-0d13c280-17cf-11eb-900f-4464c05c4bdb.png)
**RSA:** в принципе все ок.

**Общее замечание:** верните везде доктесты, их не надо было удалять.

2020-11-07 18:50 UTC, anastasiiaCher requested changes
Почти везде все ок.
Форматирвоание все еще страдает. Используйте black.

2020-11-07 18:50 UTC, anastasiiaCher commented on homework01/caesar.py
> +	for word in words:
Съехали все отступы, поправьте

2020-11-07 18:50 UTC, anastasiiaCher commented on homework01/rsa.py
> +    x = 0; old_x = 1
Для одновременного инициализирования нескольких переменных будет лучше воспользоваться синтаксисом одновременного присваивания. Например, `a, b, c = 1, 5, []` будет эквивалентно строкам:
```
a = 1
b = 5
c = []
```
Вы успешно используете такой синтаксис дальше по коду, воспользуйтесь им и здесь

2020-11-07 20:34 UTC, merged

2020-11-07 20:35 UTC, shulgadanilazxc commented on homework01/rsa.py
> +    x = 0; old_x = 1
ок

2020-11-08 11:44 UTC, anastasiiaCher commented
В 52-53 строке у вас как раз и поехали отступы:
![image](https://user-images.githubusercontent.com/28839610/98463977-a203bc00-21d0-11eb-9609-567a7ae5dedc.png)
На это блэк и ругается. Нажав merge, вы залили в ветку master файлик с нерабочим Цезарем (из-за отступов).
Все остальное - ок.

2020-11-09 18:39 UTC, anastasiiaCher commented
Первая работа зачтена.